---
title: "Trío Tristeza"
subtitle: "**ODS 11: Lograr que las ciudades y los asentamientos humanos sean inclusivos, seguros, resilientes y sostenibles**: Para que la ciudad deje de pensarse como una mercancía para convertirse en un derecho"
author: 
  - "Herrera Díaz Arturo" 
  - "León García Eduardo Levi"
  - "Martínez Torres Luis Donaldo"
format:
  revealjs:
    theme: simple
    transition: slide
    scrollable: true
    css: custom.css
---

## Pregunta guía, datos y enfoque

¿Qué tan cercana está la Ciudad de México de cumplir las metas del ODS 11 para convertirse en un espacio donde la movilidad, la seguridad, la inclusión, y la sostenibilidad sean un derecho y no un privilegio?

 - Identificar las zonas de la CDMX en las que vivir, trabajar y descansar pueda suceder en en recorridos de menos de 15 minutos (Moreno, 2021), ya sea a pie o en bicicleta, desde el hogar.
 - A partir del análisis anterior, identificar la asimetría urbana (Ziccardi-Contigiani y Dammert, 2024) relacionada con la movilidad, la inclusividad y la sostenibilidad.
 - Visibilizar las relaciones espaciales de inclusividad, seguridad, resiliencia y sostenibilidad que busca el objetivo del OSD 11.

Datos relacionados con la cercanía de transporte, la infraestructura urbana, la oferta de servicios, el volumen de la población y la conectividad digital. La mayoría de ellos obtenidos de la Plataforma de Datos Abiertos CDMX y del INEGI. Realizando un cruce espacial de las 4 variables propuestas por Moreno (2021): Proximidad, diversidad, densidad y digitalizacion; que en su conjunto buscan evidenciar la existencia de ciudades habitables.

## Dudas o puntos de orientación

Necesidad de claridad

 - ¿Podríamos expicar un ejemplo o hacer que el usuario pueda sacar las conclusiones a partir de lo que representan los datos en el mapa?

Dudas de enfoque

 - Unidad básica de análisis espacial: manzana. Visualización a partir de: colonias.
 - Es un análisis espacial simple en donde la representación de diferentes variables permitirá al usuario identificar que tan cerca vive de la meta en el ODS 11 para el 2030

